#!/bin/sh

### BEGIN INIT INFO
# Provides:          hornetq
# Default-Start:     3 5
# Default-Stop:      0 1 2 6
# Short-Description: Hornetq
# Description:       Start the Hornetq message broker
### END INIT INFO

# Check for existence of needed config file and read it
CONFIG=/etc/sysconfig/hornetq
test -e "$CONFIG" || { echo "$CONFIG not existing";
    if [ "$1" = "stop" ]; then exit 0;
    else exit 6; fi; }
test -r "$CONFIG" || { echo "$CONFIG not readable. Perhaps you forgot 'sudo'?";
    if [ "$1" = "stop" ]; then exit 0;
    else exit 6; fi; }

PID_FILE="/var/run/hornetq.pid"

USER=hornetq

# Source function library.
. /etc/init.d/functions

# Read config   
[ -f "$CONFIG" ] && . "$CONFIG"

RETVAL=0

start() {
    echo -n "Starting HornetQ "
    /sbin/runuser -s /bin/sh "$USER" -c "java $JVM_ARGS -classpath $CLASSPATH org.hornetq.integration.bootstrap.HornetQBootstrapServer hornetq-beans.xml" > /dev/null 2>&1 &
    PID=$!
    RETVAL=$?
    if [ $RETVAL = 0 ]; then
        echo "$PID" > $PID_FILE
        success
    else
        failure
    fi
    echo
}

stop() {
    echo -n "Shutting down HornetQ "
    killproc -p "$PID_FILE" -d 20 hornetq
    RETVAL=$?
    echo
}

case "$1" in
    start)
    start
    ;;
    stop)
    stop
    ;;
    restart)
    stop
    start
    ;;
    status)
    status -p $PID_FILE HornetQ
    RETVAL=$?    
    ;;
    *)
    echo "Usage: $0 {start|stop|status|try-restart|restart|force-reload|reload|probe}"
    exit 1
    ;;
esac
exit $RETVAL
